# Generated by Django 4.2.2 on 2023-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0004_remove_product_stock_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachineslot',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
