# Generated by Django 4.2.2 on 2023-07-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0005_remove_vendingmachineslot_quantity_stock_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.product', unique=True),
        ),
    ]
