# Generated by Django 4.2.2 on 2023-07-21 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0007_alter_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 7, 21, 15, 13, 9, 170249, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
