# Generated by Django 4.2.2 on 2023-07-24 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0009_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachineslot',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
